package prompts

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/kieranajp/qrouton/internal/sessionpaths"
)

// Asset names Render produces for the two mode prompts. Callers choose which of
// them owns the discovery files by passing it to Stamp as primary.
const (
	OrchestratorAsset = "ORCHESTRATOR.md"
	AssistantAsset    = "ASSISTANT.md"
)

const (
	claudeDiscoveryName = "CLAUDE.md"
	agentsDiscoveryName = "AGENTS.md"

	skillsPathPrefix = "skills/"
	claudeSkillsDir  = ".claude"
	agentsSkillsDir  = ".agents"
	skillsDirName    = "skills"

	tomlExtension = ".toml"

	markerNote = "Generated by qrouton at launch. Do not edit here -- edit prompts/ in the qrouton repo; this file is overwritten on next launch."

	// MarkerText is the HTML-comment form written into Markdown assets.
	MarkerText = "<!-- " + markerNote + " -->\n"

	tomlMarkerText = "# " + markerNote + "\n"

	// markerNeedle matches both forms, so ownership survives a marker reword.
	markerNeedle = "Generated by qrouton"

	frontmatterFence = "---\n"
	frontmatterClose = "\n---\n"

	// handoffHeader introduces the assistant's escalation brief when Stamp
	// appends it to the primary mode prompt. Because assets are re-stamped on
	// every launch, the brief stays in the system prompt for the session's
	// life — the assistant prompt tells it to keep the brief short.
	handoffHeader = "\n\n## Handoff brief\n\n"

	dirMode  = 0o755
	fileMode = 0o644
)

type assetLink struct {
	link   string
	target string
}

// Stamp renders all prompts and links primary into both discovery locations.
// Existing unmarked files and symlinks are user-owned and never replaced.
func Stamp(ctx context.Context, dir string, loader PromptLoader, primary string) error {
	canonical := sessionpaths.CanonicalPrompts(dir)
	loaded, err := loader.List(ctx)
	if err != nil {
		return err
	}
	handoff := handoffSection(dir)

	var links []assetLink
	seenLinks := make(map[string]bool)
	for _, prompt := range loaded {
		rendered, err := Render(prompt)
		if err != nil {
			return err
		}
		for _, asset := range rendered {
			destination, assetLinks := assetDestination(dir, canonical, asset.Path, primary)
			for _, link := range assetLinks {
				if seenLinks[link.link] {
					continue
				}
				seenLinks[link.link] = true
				links = append(links, link)
			}
			if err := ensureAssetOurs(canonical, destination); err != nil {
				return err
			}
			if err := os.MkdirAll(filepath.Dir(destination), dirMode); err != nil {
				return err
			}
			content := mark(destination, asset.Content)
			if asset.Path == primary {
				content = append(content, handoff...)
			}
			if err := os.WriteFile(destination, content, fileMode); err != nil {
				return err
			}
		}
	}

	for _, link := range links {
		if err := ensureAssetLink(link); err != nil {
			return err
		}
	}
	return nil
}

func handoffSection(dir string) []byte {
	content, err := os.ReadFile(sessionpaths.Handoff(dir))
	if err != nil || len(strings.TrimSpace(string(content))) == 0 {
		return nil
	}
	return append([]byte(handoffHeader), content...)
}

func assetDestination(dir, canonical, assetPath, primary string) (string, []assetLink) {
	switch {
	case assetPath == OrchestratorAsset || assetPath == AssistantAsset:
		destination := filepath.Join(canonical, assetPath)
		if assetPath != primary {
			return destination, nil
		}
		return destination, []assetLink{
			{link: filepath.Join(dir, claudeDiscoveryName), target: destination},
			{link: filepath.Join(dir, agentsDiscoveryName), target: destination},
		}

	case strings.HasPrefix(assetPath, skillsPathPrefix):
		destination := filepath.Join(canonical, filepath.FromSlash(assetPath))
		skillName, _, _ := strings.Cut(strings.TrimPrefix(assetPath, skillsPathPrefix), "/")
		skillDir := filepath.Join(canonical, skillsDirName, skillName)
		return destination, []assetLink{
			{link: filepath.Join(dir, claudeSkillsDir, skillsDirName, skillName), target: skillDir},
			{link: filepath.Join(dir, agentsSkillsDir, skillsDirName, skillName), target: skillDir},
		}

	default:
		return filepath.Join(dir, filepath.FromSlash(assetPath)), nil
	}
}

// ensureAssetOurs guards a write into the user's own tree. Everything under the
// canonical directory is qrouton's, marker or not; the provider agent files
// land beside whatever the user keeps in .claude and .codex.
func ensureAssetOurs(canonical, destination string) error {
	if strings.HasPrefix(destination, canonical+string(filepath.Separator)) {
		return nil
	}
	ours, err := ownedByUs(destination)
	if err != nil {
		return err
	}
	if !ours {
		return fmt.Errorf("%w: %s", ErrUserOwnedAsset, destination)
	}
	return nil
}

// ownedByUs reports whether the path is qrouton's to replace: absent, a link we
// stamped, or content carrying the marker. A user's own symlink deserves the
// same protection as their regular files, so unless the link is provably ours
// its resolved content has to carry the marker.
func ownedByUs(path string) (bool, error) {
	info, err := os.Lstat(path)
	if os.IsNotExist(err) {
		return true, nil
	}
	if err != nil {
		return false, err
	}
	if info.Mode()&os.ModeSymlink != 0 && ownAssetLink(path) {
		return true, nil
	}
	content, err := os.ReadFile(path)
	if err != nil {
		return false, nil
	}
	return strings.Contains(string(content), markerNeedle), nil
}

func ensureAssetLink(link assetLink) error {
	if err := os.MkdirAll(filepath.Dir(link.link), dirMode); err != nil {
		return err
	}
	ours, err := ownedByUs(link.link)
	if err != nil {
		return err
	}
	if !ours {
		return fmt.Errorf("%w: %s", ErrUserOwnedAsset, link.link)
	}
	if err := os.Remove(link.link); err != nil && !os.IsNotExist(err) {
		return err
	}

	relative, err := filepath.Rel(filepath.Dir(link.link), link.target)
	if err != nil {
		return err
	}
	return os.Symlink(relative, link.link)
}

// ownAssetLink reports whether an existing symlink is one qrouton stamped: our
// links always point into the session's canonical directory. Judging by the
// link's own destination (not its resolved content) keeps this true even for
// links left dangling by a canonical-asset rename.
func ownAssetLink(link string) bool {
	destination, err := os.Readlink(link)
	if err != nil {
		return false
	}
	if !filepath.IsAbs(destination) {
		destination = filepath.Join(filepath.Dir(link), destination)
	}
	separator := string(filepath.Separator)
	return strings.Contains(filepath.Clean(destination), separator+sessionpaths.DirName+separator)
}

// mark prefixes content with the generated-by marker in the comment syntax the
// destination's format understands, preserving YAML frontmatter's requirement
// that it start on line one. A format whose comment syntax we cannot assume —
// a skill shipping a script or an asset — is written exactly as authored.
func mark(destination string, content []byte) []byte {
	switch filepath.Ext(destination) {
	case tomlExtension:
		return append([]byte(tomlMarkerText), content...)
	case promptFileExt:
		return markMarkdown(string(content))
	default:
		return content
	}
}

func markMarkdown(text string) []byte {
	if strings.HasPrefix(text, frontmatterFence) {
		if index := strings.Index(text[len(frontmatterFence):], frontmatterClose); index >= 0 {
			position := len(frontmatterFence) + index + len(frontmatterClose)
			return []byte(text[:position] + MarkerText + text[position:])
		}
	}
	return []byte(MarkerText + "\n" + text)
}
