package prompts

// Stamping is the other half of rendering: Render turns one canonical prompt
// into provider-shaped assets, Stamp lays those assets out on disk as a runner
// discovery tree. Both live here so a session launch and a prompt eval
// materialise byte-identical trees — an eval that graded a different layout
// than sessions get would be grading the wrong thing.

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/kieranajp/qrouton/internal/sessionpaths"
)

// Asset names Render produces for the two mode prompts. Callers choose which of
// them owns the discovery files by passing it to Stamp as primary.
const (
	OrchestratorAsset = "ORCHESTRATOR.md"
	AssistantAsset    = "ASSISTANT.md"
)

const (
	claudeDiscoveryName = "CLAUDE.md"
	agentsDiscoveryName = "AGENTS.md"

	skillsPathPrefix = "skills/"
	claudeSkillsDir  = ".claude"
	agentsSkillsDir  = ".agents"
	skillsDirName    = "skills"

	tomlExtension = ".toml"

	// markerNote is the one sentence a reader of a stamped file needs: this is
	// not the source of truth, and editing it here achieves nothing.
	markerNote = "Generated by qrouton at launch. Do not edit here -- edit prompts/ in the qrouton repo; this file is overwritten on next launch."

	// MarkerText is the HTML-comment form written into Markdown assets. It is
	// also the needle ensureAssetLink looks for when deciding whether a file it
	// is about to replace is one of ours.
	MarkerText = "<!-- " + markerNote + " -->\n"

	tomlMarkerText = "# " + markerNote + "\n"

	// markerNeedle matches both forms, so ownership survives a marker reword.
	markerNeedle = "Generated by qrouton"

	frontmatterFence = "---\n"
	frontmatterClose = "\n---\n"

	dirMode  = 0o755
	fileMode = 0o644
)

type assetLink struct {
	link   string
	target string
}

// Stamp renders every prompt the loader supplies into dir's discovery tree.
// primary names the mode prompt that owns CLAUDE.md and AGENTS.md; the other
// mode prompt is still written under the canonical directory, so a session can
// escalate between modes without relaunching.
//
// User-authored files are never replaced: an existing discovery file or symlink
// that does not carry the qrouton marker is an error, not something to
// overwrite.
func Stamp(ctx context.Context, dir string, loader PromptLoader, primary string) error {
	canonical := sessionpaths.CanonicalPrompts(dir)
	loaded, err := loader.List(ctx)
	if err != nil {
		return err
	}

	var links []assetLink
	for _, prompt := range loaded {
		rendered, err := Render(prompt)
		if err != nil {
			return err
		}
		for _, asset := range rendered {
			destination, assetLinks := assetDestination(dir, canonical, asset.Path, primary)
			links = append(links, assetLinks...)
			if err := os.MkdirAll(filepath.Dir(destination), dirMode); err != nil {
				return err
			}
			if err := os.WriteFile(destination, mark(destination, asset.Content), fileMode); err != nil {
				return err
			}
		}
	}

	for _, link := range links {
		if err := ensureAssetLink(link); err != nil {
			return err
		}
	}
	return nil
}

// assetDestination places one rendered asset and reports the discovery links
// that should point at it. Mode prompts and skills are canonicalised and
// linked; provider agent files are written where Render already addressed them.
func assetDestination(dir, canonical, assetPath, primary string) (string, []assetLink) {
	switch {
	case assetPath == OrchestratorAsset || assetPath == AssistantAsset:
		destination := filepath.Join(canonical, assetPath)
		if assetPath != primary {
			return destination, nil
		}
		return destination, []assetLink{
			{link: filepath.Join(dir, claudeDiscoveryName), target: destination},
			{link: filepath.Join(dir, agentsDiscoveryName), target: destination},
		}

	case strings.HasPrefix(assetPath, skillsPathPrefix):
		destination := filepath.Join(canonical, filepath.FromSlash(assetPath))
		skillRel := filepath.FromSlash(strings.TrimPrefix(assetPath, skillsPathPrefix))
		return destination, []assetLink{
			{link: filepath.Join(dir, claudeSkillsDir, skillsDirName, skillRel), target: destination},
			{link: filepath.Join(dir, agentsSkillsDir, skillsDirName, skillRel), target: destination},
		}

	default:
		return filepath.Join(dir, filepath.FromSlash(assetPath)), nil
	}
}

func ensureAssetLink(link assetLink) error {
	if err := os.MkdirAll(filepath.Dir(link.link), dirMode); err != nil {
		return err
	}
	if info, err := os.Lstat(link.link); err == nil {
		// A user's own symlink deserves the same protection as their regular
		// files: unless the link is provably ours, its (resolved) content must
		// carry the qrouton marker before we replace it.
		ours := info.Mode()&os.ModeSymlink != 0 && ownAssetLink(link.link)
		if !ours {
			content, readErr := os.ReadFile(link.link)
			if readErr != nil || !strings.Contains(string(content), markerNeedle) {
				return fmt.Errorf("%w: %s", ErrUserOwnedAsset, link.link)
			}
		}
		if err := os.Remove(link.link); err != nil {
			return err
		}
	} else if !os.IsNotExist(err) {
		return err
	}

	relative, err := filepath.Rel(filepath.Dir(link.link), link.target)
	if err != nil {
		return err
	}
	return os.Symlink(relative, link.link)
}

// ownAssetLink reports whether an existing symlink is one qrouton stamped: our
// links always point into the session's canonical directory. Judging by the
// link's own destination (not its resolved content) keeps this true even for
// links left dangling by a canonical-asset rename.
func ownAssetLink(link string) bool {
	destination, err := os.Readlink(link)
	if err != nil {
		return false
	}
	if !filepath.IsAbs(destination) {
		destination = filepath.Join(filepath.Dir(link), destination)
	}
	separator := string(filepath.Separator)
	return strings.Contains(filepath.Clean(destination), separator+sessionpaths.DirName+separator)
}

// mark prefixes content with the generated-by marker in the comment syntax the
// destination's format understands, preserving YAML frontmatter's requirement
// that it start on line one.
func mark(destination string, content []byte) []byte {
	if filepath.Ext(destination) == tomlExtension {
		return append([]byte(tomlMarkerText), content...)
	}
	text := string(content)
	if strings.HasPrefix(text, frontmatterFence) {
		if index := strings.Index(text[len(frontmatterFence):], frontmatterClose); index >= 0 {
			position := len(frontmatterFence) + index + len(frontmatterClose)
			return []byte(text[:position] + MarkerText + text[position:])
		}
	}
	return []byte(MarkerText + "\n" + text)
}
