package main

import (
	"embed"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// Prompt assets embedded into the binary and stamped into every session at launch (S002 #3).
// all: prefix is required — plain //go:embed skips dot-dirs, and we ship .claude/.
//
//go:embed all:assets
var assetsFS embed.FS

const assetMarker = "<!-- Generated by qrouton at launch. Do not edit here — edit assets/ in the qrouton repo; this file is overwritten on next launch. -->\n"

// stampAssets walks the embedded assets/ tree into the session root, overwriting each file
// (qrouton owns exactly these paths: CLAUDE.md, .claude/skills/qrspi-*, .claude/agents/qrspi-*).
// Files outside the embed tree are never touched, so user/onetech .claude content survives.
func stampAssets(dir string) error {
	return fs.WalkDir(assetsFS, "assets", func(p string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		b, err := assetsFS.ReadFile(p)
		if err != nil {
			return err
		}
		dst := filepath.Join(dir, strings.TrimPrefix(p, "assets/"))
		if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
			return err
		}
		return os.WriteFile(dst, mark(b), 0o644)
	})
}

// mark inserts the generated-by marker after any YAML frontmatter block (skills/agents need
// their --- on line 1), else prepends it. Keeps every asset stamped without per-file discipline.
func mark(content []byte) []byte {
	s := string(content)
	if strings.HasPrefix(s, "---\n") {
		if i := strings.Index(s[4:], "\n---\n"); i >= 0 {
			pos := 4 + i + len("\n---\n")
			return []byte(s[:pos] + assetMarker + s[pos:])
		}
	}
	return []byte(assetMarker + "\n" + s)
}
