package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestStampAssetsWritesOverwritesAndRespectsOwnership(t *testing.T) {
	dir := t.TempDir()

	if err := stampAssets(dir); err != nil {
		t.Fatal(err)
	}

	// owned files land, carry the marker
	claude := filepath.Join(dir, "CLAUDE.md")
	b, err := os.ReadFile(claude)
	if err != nil {
		t.Fatal("CLAUDE.md not stamped:", err)
	}
	if !strings.Contains(string(b), "Generated by qrouton") {
		t.Fatal("CLAUDE.md missing generated-by marker")
	}
	skill := filepath.Join(dir, ".claude", "skills", "qrspi-questions", "SKILL.md")
	sb, err := os.ReadFile(skill)
	if err != nil {
		t.Fatal("skill not stamped:", err)
	}
	// frontmatter must still start on line 1 — marker goes after the closing ---
	if !strings.HasPrefix(string(sb), "---\n") {
		t.Fatal("marker broke skill frontmatter (must lead with ---)")
	}

	// a non-owned .claude file and a user edit must survive a re-stamp
	foreign := filepath.Join(dir, ".claude", "settings.json")
	os.WriteFile(foreign, []byte(`{"user":true}`), 0o644)
	os.WriteFile(claude, []byte("clobber me"), 0o644)

	if err := stampAssets(dir); err != nil {
		t.Fatal(err)
	}
	if fb, _ := os.ReadFile(foreign); string(fb) != `{"user":true}` {
		t.Fatal("re-stamp touched a non-owned .claude file")
	}
	if cb, _ := os.ReadFile(claude); !strings.Contains(string(cb), "qrouton session orchestrator") {
		t.Fatal("re-stamp did not overwrite owned CLAUDE.md")
	}
}
