package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestStampAssetsWritesOverwritesAndRespectsOwnership(t *testing.T) {
	dir := t.TempDir()

	if err := stampAssets(dir); err != nil {
		t.Fatal(err)
	}

	// Runner discovery files are relative links to one canonical session-local copy.
	claude := filepath.Join(dir, "CLAUDE.md")
	agents := filepath.Join(dir, "AGENTS.md")
	for _, p := range []string{claude, agents} {
		if info, err := os.Lstat(p); err != nil || info.Mode()&os.ModeSymlink == 0 {
			t.Fatalf("%s is not a symlink: %v", p, err)
		}
	}
	b, err := os.ReadFile(claude)
	if err != nil {
		t.Fatal("CLAUDE.md not stamped:", err)
	}
	if !strings.Contains(string(b), "Generated by qrouton") {
		t.Fatal("CLAUDE.md missing generated-by marker")
	}
	for _, want := range []string{
		"Present one simple workflow: **Research → Plan → Implement**",
		"Orchestrate; do not absorb the work",
		"delegate the approved plan to one implementation lead",
		"use qrouton's `open_file` MCP tool",
	} {
		if !strings.Contains(string(b), want) {
			t.Fatalf("orchestrator prompt missing %q", want)
		}
	}
	skill := filepath.Join(dir, ".claude", "skills", "qrspi-questions", "SKILL.md")
	codexSkill := filepath.Join(dir, ".agents", "skills", "qrspi-questions", "SKILL.md")
	for _, p := range []string{skill, codexSkill} {
		if info, err := os.Lstat(p); err != nil || info.Mode()&os.ModeSymlink == 0 {
			t.Fatalf("%s is not a symlink: %v", p, err)
		}
	}
	sb, err := os.ReadFile(skill)
	if err != nil {
		t.Fatal("skill not stamped:", err)
	}
	// frontmatter must still start on line 1 — marker goes after the closing ---
	if !strings.HasPrefix(string(sb), "---\n") {
		t.Fatal("marker broke skill frontmatter (must lead with ---)")
	}
	if target, _ := os.Readlink(skill); filepath.IsAbs(target) {
		t.Fatal("skill link must be relative for portable sessions")
	}
	agentNames := []string{
		"qrspi-researcher", "qrspi-research-lead", "qrspi-planning-lead", "qrspi-implementation-lead",
		"codebase-researcher", "pattern-finder", "thoughts-researcher", "external-researcher", "test-verifier", "code-reviewer",
	}
	for _, name := range agentNames {
		if cb, err := os.ReadFile(filepath.Join(dir, ".codex", "agents", name+".toml")); err != nil {
			t.Fatalf("Codex agent adapter %s not stamped: %v", name, err)
		} else if !strings.HasPrefix(string(cb), "# Generated by qrouton") {
			t.Fatalf("Codex agent adapter %s does not have valid TOML comment marker", name)
		}
	}
	for _, name := range agentNames {
		if _, err := os.ReadFile(filepath.Join(dir, ".claude", "agents", name+".md")); err != nil {
			t.Fatalf("Claude agent adapter %s not stamped: %v", name, err)
		}
	}

	// a non-owned .claude file and a user edit must survive a re-stamp
	foreign := filepath.Join(dir, ".claude", "settings.json")
	os.WriteFile(foreign, []byte(`{"user":true}`), 0o644)
	os.WriteFile(claude, []byte("clobber me"), 0o644)

	if err := stampAssets(dir); err != nil {
		t.Fatal(err)
	}
	if fb, _ := os.ReadFile(foreign); string(fb) != `{"user":true}` {
		t.Fatal("re-stamp touched a non-owned .claude file")
	}
	if cb, _ := os.ReadFile(claude); !strings.Contains(string(cb), "# qrouton orchestrator") {
		t.Fatal("re-stamp did not overwrite owned CLAUDE.md")
	}
}

func TestStampAssetsRefusesUserOwnedDiscoveryFile(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "AGENTS.md"), []byte("user instructions"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := stampAssets(dir); err == nil || !strings.Contains(err.Error(), "user-owned") {
		t.Fatalf("expected user-owned conflict, got %v", err)
	}
}
