package evalharness

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const marker = "<!-- Generated by qrouton eval. Source snapshot; do not edit. -->\n"

type assetLink struct {
	link   string
	target string
}

func CopyTree(src, dst string) error {
	return filepath.WalkDir(src, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}

		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		destination := filepath.Join(dst, rel)

		if entry.IsDir() {
			return os.MkdirAll(destination, 0o755)
		}
		if entry.Type()&os.ModeSymlink != 0 {
			target, err := os.Readlink(path)
			if err != nil {
				return err
			}
			return os.Symlink(target, destination)
		}

		return copyFile(path, destination)
	})
}

func copyFile(src, dst string) error {
	input, err := os.Open(src)
	if err != nil {
		return err
	}
	defer input.Close()

	output, err := os.OpenFile(dst, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o644)
	if err != nil {
		return err
	}

	_, copyErr := io.Copy(output, input)
	closeErr := output.Close()
	if copyErr != nil {
		return copyErr
	}
	return closeErr
}

// MaterializeAssets mirrors launch.StampAssets' Claude and Codex discovery layout
// using a caller-selected source directory rather than the embedded assets.
func MaterializeAssets(assetsDir, workspace, snapshot string) (string, error) {
	if err := CopyTree(assetsDir, snapshot); err != nil {
		return "", err
	}

	hash, err := HashTree(snapshot)
	if err != nil {
		return "", err
	}

	canonical := filepath.Join(workspace, ".qrouton", "qrspi")
	var links []assetLink
	err = filepath.WalkDir(assetsDir, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			return nil
		}

		rel, err := filepath.Rel(assetsDir, path)
		if err != nil {
			return err
		}
		if rel == "zellij-config.kdl" {
			return nil
		}

		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}

		destination, newLinks := assetDestination(workspace, canonical, rel)
		links = append(links, newLinks...)
		if err := os.MkdirAll(filepath.Dir(destination), 0o755); err != nil {
			return err
		}

		stamped := markAsset(content)
		if filepath.Ext(destination) == ".toml" {
			stamped = append([]byte("# Generated by qrouton eval.\n"), content...)
		}
		return os.WriteFile(destination, stamped, 0o644)
	})
	if err != nil {
		return "", err
	}

	for _, link := range links {
		if err := createRelativeLink(link); err != nil {
			return "", err
		}
	}
	return hash, nil
}

func markAsset(content []byte) []byte {
	text := string(content)
	if strings.HasPrefix(text, "---\n") {
		if index := strings.Index(text[4:], "\n---\n"); index >= 0 {
			position := 4 + index + len("\n---\n")
			return []byte(text[:position] + marker + text[position:])
		}
	}
	return append([]byte(marker+"\n"), content...)
}

func assetDestination(workspace, canonical, rel string) (string, []assetLink) {
	if rel == "CLAUDE.md" {
		destination := filepath.Join(canonical, "ORCHESTRATOR.md")
		links := []assetLink{
			{link: filepath.Join(workspace, "CLAUDE.md"), target: destination},
			{link: filepath.Join(workspace, "AGENTS.md"), target: destination},
		}
		return destination, links
	}

	skillsPrefix := filepath.Join(".claude", "skills") + string(filepath.Separator)
	if strings.HasPrefix(rel, skillsPrefix) {
		skillRel := strings.TrimPrefix(rel, skillsPrefix)
		destination := filepath.Join(canonical, "skills", skillRel)
		links := []assetLink{
			{link: filepath.Join(workspace, ".claude", "skills", skillRel), target: destination},
			{link: filepath.Join(workspace, ".agents", "skills", skillRel), target: destination},
		}
		return destination, links
	}

	return filepath.Join(workspace, rel), nil
}

func createRelativeLink(link assetLink) error {
	if err := os.MkdirAll(filepath.Dir(link.link), 0o755); err != nil {
		return err
	}
	relativeTarget, err := filepath.Rel(filepath.Dir(link.link), link.target)
	if err != nil {
		return err
	}
	return os.Symlink(relativeTarget, link.link)
}

func HashTree(root string) (string, error) {
	var files []string
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if !entry.IsDir() {
			files = append(files, path)
		}
		return nil
	})
	if err != nil {
		return "", err
	}

	sort.Strings(files)
	hash := sha256.New()
	for _, path := range files {
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return "", err
		}
		if _, err := fmt.Fprintln(hash, filepath.ToSlash(rel)); err != nil {
			return "", err
		}

		content, err := os.ReadFile(path)
		if err != nil {
			return "", err
		}
		if _, err := hash.Write(content); err != nil {
			return "", err
		}
	}

	return hex.EncodeToString(hash.Sum(nil)), nil
}
