package launch

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/kieranajp/qrouton/internal/session"
)

func TestStampAssetsWritesOverwritesAndRespectsOwnership(t *testing.T) {
	dir := t.TempDir()

	if err := StampAssets(dir); err != nil {
		t.Fatal(err)
	}

	// Runner discovery files are relative links to one canonical session-local copy.
	claude := filepath.Join(dir, "CLAUDE.md")
	agents := filepath.Join(dir, "AGENTS.md")
	for _, p := range []string{claude, agents} {
		if info, err := os.Lstat(p); err != nil || info.Mode()&os.ModeSymlink == 0 {
			t.Fatalf("%s is not a symlink: %v", p, err)
		}
	}
	b, err := os.ReadFile(claude)
	if err != nil {
		t.Fatal("CLAUDE.md not stamped:", err)
	}
	if !strings.Contains(string(b), "Generated by qrouton") {
		t.Fatal("CLAUDE.md missing generated-by marker")
	}
	for _, want := range []string{
		"Present one simple workflow: **Research → Plan → Implement**",
		"Orchestrate; do not absorb the work",
		"delegate the approved plan to one implementation lead",
		"use qrouton's `open_file` MCP tool",
	} {
		if !strings.Contains(string(b), want) {
			t.Fatalf("orchestrator prompt missing %q", want)
		}
	}
	skill := filepath.Join(dir, ".claude", "skills", "qrspi-questions", "SKILL.md")
	codexSkill := filepath.Join(dir, ".agents", "skills", "qrspi-questions", "SKILL.md")
	for _, p := range []string{skill, codexSkill} {
		if info, err := os.Lstat(p); err != nil || info.Mode()&os.ModeSymlink == 0 {
			t.Fatalf("%s is not a symlink: %v", p, err)
		}
	}
	sb, err := os.ReadFile(skill)
	if err != nil {
		t.Fatal("skill not stamped:", err)
	}
	// frontmatter must still start on line 1 — marker goes after the closing ---
	if !strings.HasPrefix(string(sb), "---\n") {
		t.Fatal("marker broke skill frontmatter (must lead with ---)")
	}
	if target, _ := os.Readlink(skill); filepath.IsAbs(target) {
		t.Fatal("skill link must be relative for portable sessions")
	}
	agentNames := []string{
		"qrspi-researcher", "qrspi-research-lead", "qrspi-planning-lead", "qrspi-implementation-lead",
		"codebase-researcher", "pattern-finder", "thoughts-researcher", "external-researcher", "test-verifier", "code-reviewer",
	}
	for _, name := range agentNames {
		if cb, err := os.ReadFile(filepath.Join(dir, ".codex", "agents", name+".toml")); err != nil {
			t.Fatalf("Codex agent adapter %s not stamped: %v", name, err)
		} else if !strings.HasPrefix(string(cb), "# Generated by qrouton") {
			t.Fatalf("Codex agent adapter %s does not have valid TOML comment marker", name)
		}
	}
	for _, name := range agentNames {
		if _, err := os.ReadFile(filepath.Join(dir, ".claude", "agents", name+".md")); err != nil {
			t.Fatalf("Claude agent adapter %s not stamped: %v", name, err)
		}
	}

	// a non-owned .claude file and a user edit must survive a re-stamp
	foreign := filepath.Join(dir, ".claude", "settings.json")
	os.WriteFile(foreign, []byte(`{"user":true}`), 0o644)
	os.WriteFile(claude, []byte("clobber me"), 0o644)

	if err := StampAssets(dir); err != nil {
		t.Fatal(err)
	}
	if fb, _ := os.ReadFile(foreign); string(fb) != `{"user":true}` {
		t.Fatal("re-stamp touched a non-owned .claude file")
	}
	if cb, _ := os.ReadFile(claude); !strings.Contains(string(cb), "# qrouton orchestrator") {
		t.Fatal("re-stamp did not overwrite owned CLAUDE.md")
	}
}

func TestStampAssetsLinksDiscoveryToSessionMode(t *testing.T) {
	// Default (no manifest) points discovery at the RPI orchestrator, and the
	// assistant prompt is still stamped for later escalation.
	rpi := t.TempDir()
	if err := StampAssets(rpi); err != nil {
		t.Fatal(err)
	}
	assertLinkTargetContains(t, filepath.Join(rpi, "CLAUDE.md"), "ORCHESTRATOR.md")
	if _, err := os.Stat(filepath.Join(rpi, ".qrouton", "qrspi", "ASSISTANT.md")); err != nil {
		t.Fatalf("assistant prompt not stamped for escalation: %v", err)
	}

	// An assistant manifest flips CLAUDE.md/AGENTS.md to the assistant prompt
	// while the orchestrator stays available under .qrouton.
	asst := t.TempDir()
	if err := os.WriteFile(filepath.Join(asst, "qrouton.json"), []byte(`{"mode":"assistant"}`), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := StampAssets(asst); err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{"CLAUDE.md", "AGENTS.md"} {
		assertLinkTargetContains(t, filepath.Join(asst, name), "ASSISTANT.md")
	}
	if _, err := os.Stat(filepath.Join(asst, ".qrouton", "qrspi", "ORCHESTRATOR.md")); err != nil {
		t.Fatalf("orchestrator prompt not stamped for escalation: %v", err)
	}
	if b, err := os.ReadFile(filepath.Join(asst, "CLAUDE.md")); err != nil || !strings.Contains(string(b), "qrouton assistant") {
		t.Fatalf("assistant discovery not resolving to assistant prompt: %v\n%s", err, b)
	}
}

// The S004 regression guard: escalation rewrites the manifest's mode, and the
// next stamp must follow the rewritten value — not revert to the mode the
// session was created with.
func TestStampAssetsFollowsModeRewrittenAfterCreation(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "qrouton.json"), []byte(`{"mode":"assistant"}`), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := StampAssets(dir); err != nil {
		t.Fatal(err)
	}
	assertLinkTargetContains(t, filepath.Join(dir, "CLAUDE.md"), "ASSISTANT.md")

	if err := session.SetMode(dir, session.ModeRPI); err != nil {
		t.Fatal(err)
	}
	if err := StampAssets(dir); err != nil {
		t.Fatal(err)
	}
	assertLinkTargetContains(t, filepath.Join(dir, "CLAUDE.md"), "ORCHESTRATOR.md")
}

// The escalation handoff: a brief at .qrouton/handoff.md rides into the
// stamped primary discovery file, so a fresh orchestrator starts holding it.
func TestStampAssetsAppendsHandoffBriefToPrimaryDiscovery(t *testing.T) {
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, ".qrouton"), 0o755); err != nil {
		t.Fatal(err)
	}
	brief := "the webhook retry brief: shared backoff clock, consumer ack deadline ruled out"
	if err := os.WriteFile(filepath.Join(dir, ".qrouton", "handoff.md"), []byte(brief), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := StampAssets(dir); err != nil {
		t.Fatal(err)
	}
	// CLAUDE.md still resolves to the primary (no manifest → orchestrator)…
	assertLinkTargetContains(t, filepath.Join(dir, "CLAUDE.md"), "ORCHESTRATOR.md")
	// …and the brief is genuinely inside what the runner discovers.
	b, err := os.ReadFile(filepath.Join(dir, "CLAUDE.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(b), brief) {
		t.Fatal("handoff brief not appended to the stamped primary discovery file")
	}
	// The non-primary mode prompt stays pristine.
	ab, err := os.ReadFile(filepath.Join(dir, ".qrouton", "qrspi", "ASSISTANT.md"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(ab), brief) {
		t.Fatal("handoff brief leaked into the non-primary mode prompt")
	}
}

func assertLinkTargetContains(t *testing.T, link, want string) {
	t.Helper()
	target, err := os.Readlink(link)
	if err != nil {
		t.Fatalf("%s is not a symlink: %v", link, err)
	}
	if !strings.Contains(target, want) {
		t.Fatalf("%s links to %q, want it to contain %q", link, target, want)
	}
}

func TestStampAssetsRefusesUserOwnedDiscoveryFile(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "AGENTS.md"), []byte("user instructions"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := StampAssets(dir); err == nil || !strings.Contains(err.Error(), "user-owned") {
		t.Fatalf("expected user-owned conflict, got %v", err)
	}
}

func TestStampAssetsRefusesUserOwnedSymlink(t *testing.T) {
	dir := t.TempDir()
	mine := filepath.Join(dir, "my-instructions.md")
	if err := os.WriteFile(mine, []byte("user instructions"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(mine, filepath.Join(dir, "AGENTS.md")); err != nil {
		t.Fatal(err)
	}
	if err := StampAssets(dir); err == nil || !strings.Contains(err.Error(), "user-owned") {
		t.Fatalf("expected user-owned conflict for user symlink, got %v", err)
	}
	if b, err := os.ReadFile(mine); err != nil || string(b) != "user instructions" {
		t.Fatalf("user-linked content damaged: %q %v", b, err)
	}
}
