package launch

import (
	"embed"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// Prompt assets are embedded as the distribution source. At launch they are written once into
// .qrouton/qrspi and exposed through each runner's native discovery paths using relative symlinks.
//
//go:embed all:assets
var assetsFS embed.FS

const assetMarker = "<!-- Generated by qrouton at launch. Do not edit here -- edit assets/ in the qrouton repo; this file is overwritten on next launch. -->\n"

type assetLink struct {
	link   string
	target string
}

// StampAssets refreshes qrouton's canonical, session-local assets and their runner adapters.
// Existing generated regular files are migrated to links; user-authored files are never replaced.
func StampAssets(dir string) error {
	canonical := filepath.Join(dir, ".qrouton", "qrspi")
	var links []assetLink
	err := fs.WalkDir(assetsFS, "assets", func(p string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		b, err := assetsFS.ReadFile(p)
		if err != nil {
			return err
		}
		rel := strings.TrimPrefix(p, "assets/")
		if rel == "zellij-config.kdl" {
			return nil // stamped by writeSupport without a Markdown ownership marker
		}
		var dst string
		switch {
		case rel == "AGENTS.md":
			dst = filepath.Join(canonical, "ORCHESTRATOR.md")
			links = append(links,
				assetLink{filepath.Join(dir, "CLAUDE.md"), dst},
				assetLink{filepath.Join(dir, "AGENTS.md"), dst})
		case strings.HasPrefix(rel, ".claude/skills/"):
			skillRel := strings.TrimPrefix(rel, ".claude/skills/")
			dst = filepath.Join(canonical, "skills", skillRel)
			links = append(links,
				assetLink{filepath.Join(dir, ".claude", "skills", skillRel), dst},
				assetLink{filepath.Join(dir, ".agents", "skills", skillRel), dst})
		default:
			// Runner-specific adapters (custom-agent formats, for example) stay runner-specific.
			dst = filepath.Join(dir, rel)
		}
		if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
			return err
		}
		content := mark(b)
		if filepath.Ext(dst) == ".toml" {
			content = append([]byte("# Generated by qrouton at launch. Do not edit here.\n"), b...)
		}
		return os.WriteFile(dst, content, 0o644)
	})
	if err != nil {
		return err
	}
	for _, l := range links {
		if err := ensureAssetLink(l.link, l.target); err != nil {
			return err
		}
	}
	return nil
}

func ensureAssetLink(link, target string) error {
	if err := os.MkdirAll(filepath.Dir(link), 0o755); err != nil {
		return err
	}
	if info, err := os.Lstat(link); err == nil {
		if info.Mode()&os.ModeSymlink == 0 {
			b, readErr := os.ReadFile(link)
			if readErr != nil || !strings.Contains(string(b), "Generated by qrouton") {
				return fmt.Errorf("refusing to replace user-owned asset %s", link)
			}
		}
		if err := os.Remove(link); err != nil {
			return err
		}
	} else if !os.IsNotExist(err) {
		return err
	}
	rel, err := filepath.Rel(filepath.Dir(link), target)
	if err != nil {
		return err
	}
	return os.Symlink(rel, link)
}

// mark inserts the generated-by marker after YAML frontmatter, preserving its required first line.
func mark(content []byte) []byte {
	s := string(content)
	if strings.HasPrefix(s, "---\n") {
		if i := strings.Index(s[4:], "\n---\n"); i >= 0 {
			pos := 4 + i + len("\n---\n")
			return []byte(s[:pos] + assetMarker + s[pos:])
		}
	}
	return []byte(assetMarker + "\n" + s)
}
