package launch

import (
	"context"
	"embed"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/kieranajp/qrouton/prompts"
)

//go:embed all:assets
var assetsFS embed.FS

const assetMarker = "<!-- Generated by qrouton at launch. Do not edit here -- edit prompts/ in the qrouton repo; this file is overwritten on next launch. -->\n"

type assetLink struct {
	link   string
	target string
}

// StampAssets refreshes qrouton's canonical, session-local assets and their runner adapters.
// Existing generated regular files are migrated to links; user-authored files are never replaced.
func StampAssets(dir string) error {
	return StampAssetsWithLoader(context.Background(), dir, prompts.NewEmbeddedLoader())
}

// StampAssetsWithLoader allows callers and tests to supply a prompt source.
func StampAssetsWithLoader(ctx context.Context, dir string, loader prompts.PromptLoader) error {
	canonical := filepath.Join(dir, ".qrouton", "qrspi")
	var links []assetLink
	loaded, err := loader.List(ctx)
	if err != nil {
		return err
	}
	for _, prompt := range loaded {
		rendered, err := prompts.Render(prompt)
		if err != nil {
			return err
		}
		for _, asset := range rendered {
			dst := filepath.Join(dir, filepath.FromSlash(asset.Path))
			switch {
			case asset.Path == "ORCHESTRATOR.md":
				dst = filepath.Join(canonical, asset.Path)
				links = append(links,
					assetLink{filepath.Join(dir, "CLAUDE.md"), dst},
					assetLink{filepath.Join(dir, "AGENTS.md"), dst})
			case strings.HasPrefix(asset.Path, "skills/"):
				dst = filepath.Join(canonical, filepath.FromSlash(asset.Path))
				skillRel := strings.TrimPrefix(asset.Path, "skills/")
				links = append(links,
					assetLink{filepath.Join(dir, ".claude", "skills", filepath.FromSlash(skillRel)), dst},
					assetLink{filepath.Join(dir, ".agents", "skills", filepath.FromSlash(skillRel)), dst})
			}
			if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
				return err
			}
			content := mark(asset.Content)
			if filepath.Ext(dst) == ".toml" {
				content = append([]byte("# Generated by qrouton at launch. Do not edit here.\n"), asset.Content...)
			}
			if err := os.WriteFile(dst, content, 0o644); err != nil {
				return err
			}
		}
	}
	for _, l := range links {
		if err := ensureAssetLink(l.link, l.target); err != nil {
			return err
		}
	}
	return nil
}

func ensureAssetLink(link, target string) error {
	if err := os.MkdirAll(filepath.Dir(link), 0o755); err != nil {
		return err
	}
	if info, err := os.Lstat(link); err == nil {
		// A user's own symlink deserves the same protection as their regular
		// files: unless the link is provably ours, its (resolved) content must
		// carry the qrouton marker before we replace it.
		ours := info.Mode()&os.ModeSymlink != 0 && ownAssetLink(link)
		if !ours {
			b, readErr := os.ReadFile(link)
			if readErr != nil || !strings.Contains(string(b), "Generated by qrouton") {
				return fmt.Errorf("refusing to replace user-owned asset %s", link)
			}
		}
		if err := os.Remove(link); err != nil {
			return err
		}
	} else if !os.IsNotExist(err) {
		return err
	}
	rel, err := filepath.Rel(filepath.Dir(link), target)
	if err != nil {
		return err
	}
	return os.Symlink(rel, link)
}

// ownAssetLink reports whether an existing symlink is one qrouton stamped: our
// links always point into the session's .qrouton directory. Judging by the
// link's own destination (not its resolved content) keeps this true even for
// links left dangling by a canonical-asset rename.
func ownAssetLink(link string) bool {
	dest, err := os.Readlink(link)
	if err != nil {
		return false
	}
	if !filepath.IsAbs(dest) {
		dest = filepath.Join(filepath.Dir(link), dest)
	}
	sep := string(filepath.Separator)
	return strings.Contains(filepath.Clean(dest), sep+".qrouton"+sep)
}

// mark inserts the generated-by marker after YAML frontmatter, preserving its required first line.
func mark(content []byte) []byte {
	s := string(content)
	if strings.HasPrefix(s, "---\n") {
		if i := strings.Index(s[4:], "\n---\n"); i >= 0 {
			pos := 4 + i + len("\n---\n")
			return []byte(s[:pos] + assetMarker + s[pos:])
		}
	}
	return []byte(assetMarker + "\n" + s)
}
