// Command bridge writes the page's copy of the names the workbench binds: one
// constant per bound method, one per event, and the defaults the chrome payload
// is read through.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

//go:generate go run .

// Paths are the generator's own, relative to the package directory go generate
// runs it in.
const (
	desktopPackage = ".."
	statusPackage  = "../../status"
	moduleFile     = "../../../go.mod"
	generatedPage  = "../frontend/src/lib/bridge/generated.js"
)

const (
	header       = "// Code generated by internal/desktop/bridge. DO NOT EDIT."
	chromeFields = "Fields"
	defaultsName = "CHROME_DEFAULTS"
	eventSuffix  = "Event"
)

func main() {
	body, err := render(desktopPackage, statusPackage, moduleFile)
	if err != nil {
		log.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Dir(generatedPage), 0o755); err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(generatedPage, body, 0o644); err != nil {
		log.Fatal(err)
	}
}

func render(desktopDir, statusDir, modPath string) ([]byte, error) {
	desktop, err := parsePackage(desktopDir)
	if err != nil {
		return nil, err
	}
	status, err := parsePackage(statusDir)
	if err != nil {
		return nil, err
	}
	binding, err := importPath(modPath, desktopDir)
	if err != nil {
		return nil, err
	}
	defaults, err := payload(status, chromeFields)
	if err != nil {
		return nil, err
	}

	var js bytes.Buffer
	js.WriteString(header + "\n")
	js.WriteString("\n")
	// Whole names rather than a base the call sites append to: the workbench
	// greps its built pages for every bound method, and a name assembled across a
	// module boundary survives bundling as a concatenation it cannot find.
	for _, service := range services(desktop) {
		for _, method := range service.methods {
			fmt.Fprintf(&js, "export const %s = %q;\n",
				screaming(service.name)+"_"+screaming(method),
				binding+"."+service.name+"."+method)
		}
	}
	js.WriteString("\n")
	for _, event := range events(desktop) {
		fmt.Fprintf(&js, "export const %s = %q;\n", screaming(event.name), event.value)
	}
	js.WriteString("\n")
	fmt.Fprintf(&js, "/** @type {%s} */\n", defaults.typing(0))
	fmt.Fprintf(&js, "export const %s = %s;\n", defaultsName, defaults.value(0))
	return js.Bytes(), nil
}

// parsePackage reads a package's own files. Types are never resolved: the
// generator runs before the tree the desktop package embeds exists, so it may
// not ask the compiler anything.
func parsePackage(dir string) ([]*ast.File, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	fset := token.NewFileSet()
	var files []*ast.File
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		file, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, 0)
		if err != nil {
			return nil, err
		}
		files = append(files, file)
	}
	return files, nil
}

func importPath(modPath, dir string) (string, error) {
	body, err := os.ReadFile(modPath)
	if err != nil {
		return "", err
	}
	module := ""
	for _, line := range strings.Split(string(body), "\n") {
		if rest, found := strings.CutPrefix(strings.TrimSpace(line), "module "); found {
			module = strings.TrimSpace(rest)
			break
		}
	}
	if module == "" {
		return "", fmt.Errorf("%s names no module", modPath)
	}
	root, err := filepath.Abs(filepath.Dir(modPath))
	if err != nil {
		return "", err
	}
	pkg, err := filepath.Abs(dir)
	if err != nil {
		return "", err
	}
	rel, err := filepath.Rel(root, pkg)
	if err != nil {
		return "", err
	}
	return module + "/" + filepath.ToSlash(rel), nil
}

type service struct {
	name    string
	methods []string
}

func services(files []*ast.File) []service {
	declared := map[string]bool{}
	methods := map[string][]string{}
	for _, file := range files {
		for _, decl := range file.Decls {
			switch decl := decl.(type) {
			case *ast.GenDecl:
				if decl.Tok != token.TYPE {
					continue
				}
				for _, spec := range decl.Specs {
					if spec, ok := spec.(*ast.TypeSpec); ok && spec.Name.IsExported() {
						declared[spec.Name.Name] = true
					}
				}
			case *ast.FuncDecl:
				if decl.Recv == nil || len(decl.Recv.List) != 1 || !decl.Name.IsExported() {
					continue
				}
				if owner := receiver(decl.Recv.List[0].Type); owner != "" {
					methods[owner] = append(methods[owner], decl.Name.Name)
				}
			}
		}
	}
	var out []service
	for name, bound := range methods {
		if !declared[name] {
			continue
		}
		sort.Strings(bound)
		out = append(out, service{name: name, methods: bound})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].name < out[j].name })
	return out
}

func receiver(expr ast.Expr) string {
	if star, ok := expr.(*ast.StarExpr); ok {
		expr = star.X
	}
	ident, ok := expr.(*ast.Ident)
	if !ok || !ident.IsExported() {
		return ""
	}
	return ident.Name
}

type constant struct {
	name  string
	value string
}

func events(files []*ast.File) []constant {
	var out []constant
	for _, file := range files {
		for _, decl := range file.Decls {
			decl, ok := decl.(*ast.GenDecl)
			if !ok || decl.Tok != token.CONST {
				continue
			}
			for _, spec := range decl.Specs {
				spec, ok := spec.(*ast.ValueSpec)
				if !ok || len(spec.Names) != 1 || len(spec.Values) != 1 {
					continue
				}
				if !strings.HasSuffix(spec.Names[0].Name, eventSuffix) {
					continue
				}
				text, ok := spec.Values[0].(*ast.BasicLit)
				if !ok || text.Kind != token.STRING {
					continue
				}
				value, err := strconv.Unquote(text.Value)
				if err != nil {
					continue
				}
				out = append(out, constant{name: spec.Names[0].Name, value: value})
			}
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].name < out[j].name })
	return out
}

// field is one key of the chrome payload: what the page reads it as before the
// workbench has said anything, and the type that default stands for.
type field struct {
	key      string
	literal  string
	typeName string
	nested   []field
}

func (f field) typing(depth int) string {
	if f.nested == nil {
		return f.typeName
	}
	var parts []string
	for _, nested := range f.nested {
		parts = append(parts, nested.key+": "+nested.typing(depth+1))
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

func (f field) value(depth int) string {
	if f.nested == nil {
		return f.literal
	}
	pad := strings.Repeat("  ", depth+1)
	var body strings.Builder
	body.WriteString("{\n")
	for _, nested := range f.nested {
		fmt.Fprintf(&body, "%s%s: %s,\n", pad, nested.key, nested.value(depth+1))
	}
	body.WriteString(strings.Repeat("  ", depth) + "}")
	return body.String()
}

func payload(files []*ast.File, name string) (field, error) {
	structs := map[string]*ast.StructType{}
	for _, file := range files {
		for _, decl := range file.Decls {
			decl, ok := decl.(*ast.GenDecl)
			if !ok || decl.Tok != token.TYPE {
				continue
			}
			for _, spec := range decl.Specs {
				spec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				if body, ok := spec.Type.(*ast.StructType); ok {
					structs[spec.Name.Name] = body
				}
			}
		}
	}
	return record(structs, name, 0)
}

func record(structs map[string]*ast.StructType, name string, depth int) (field, error) {
	body, ok := structs[name]
	if !ok {
		return field{}, fmt.Errorf("no struct named %s", name)
	}
	if depth > 4 {
		return field{}, fmt.Errorf("%s nests too deeply to default", name)
	}
	out := field{nested: []field{}}
	for _, member := range body.Fields.List {
		key := jsonKey(member)
		if key == "" {
			continue
		}
		value, err := defaulted(structs, member.Type, key, depth)
		if err != nil {
			return field{}, fmt.Errorf("%s.%s: %w", name, key, err)
		}
		out.nested = append(out.nested, value)
	}
	return out, nil
}

func defaulted(structs map[string]*ast.StructType, expr ast.Expr, key string, depth int) (field, error) {
	switch typed := expr.(type) {
	case *ast.ArrayType:
		return field{key: key, literal: "[]", typeName: "any[]"}, nil
	case *ast.Ident:
		switch typed.Name {
		case "string":
			return field{key: key, literal: `""`, typeName: "string"}, nil
		case "bool":
			return field{key: key, literal: "false", typeName: "boolean"}, nil
		case "int", "int64", "float64":
			return field{key: key, literal: "0", typeName: "number"}, nil
		}
		nested, err := record(structs, typed.Name, depth+1)
		if err != nil {
			return field{}, err
		}
		nested.key = key
		return nested, nil
	}
	return field{}, fmt.Errorf("no default for %T", expr)
}

func jsonKey(member *ast.Field) string {
	if member.Tag == nil {
		return ""
	}
	tag, err := strconv.Unquote(member.Tag.Value)
	if err != nil {
		return ""
	}
	name, _, _ := strings.Cut(reflectTag(tag, "json"), ",")
	if name == "-" {
		return ""
	}
	return name
}

func reflectTag(tag, key string) string {
	for _, part := range strings.Fields(tag) {
		name, rest, found := strings.Cut(part, ":")
		if !found || name != key {
			continue
		}
		value, err := strconv.Unquote(rest)
		if err != nil {
			return ""
		}
		return value
	}
	return ""
}

// screaming is the JavaScript spelling of a Go name: Windows.OpenDocument is
// WINDOWS_OPEN_DOCUMENT.
func screaming(name string) string {
	var out strings.Builder
	runes := []rune(name)
	for i, r := range runes {
		if unicode.IsUpper(r) && i > 0 && (unicode.IsLower(runes[i-1]) || (i+1 < len(runes) && unicode.IsLower(runes[i+1]))) {
			out.WriteRune('_')
		}
		out.WriteRune(unicode.ToUpper(r))
	}
	return out.String()
}
