// Code generated by internal/desktop/bridge. DO NOT EDIT.

export const ASSEMBLY_BEGIN = "github.com/kieranajp/qrouton/internal/desktop.Assembly.Begin";
export const ASSEMBLY_CHECK = "github.com/kieranajp/qrouton/internal/desktop.Assembly.Check";
export const ASSEMBLY_CHECK_SLUG = "github.com/kieranajp/qrouton/internal/desktop.Assembly.CheckSlug";
export const ASSEMBLY_CREATE = "github.com/kieranajp/qrouton/internal/desktop.Assembly.Create";
export const ASSEMBLY_END = "github.com/kieranajp/qrouton/internal/desktop.Assembly.End";
export const ASSEMBLY_FETCH = "github.com/kieranajp/qrouton/internal/desktop.Assembly.Fetch";
export const ASSEMBLY_PENDING = "github.com/kieranajp/qrouton/internal/desktop.Assembly.Pending";
export const ASSEMBLY_PREFIXES = "github.com/kieranajp/qrouton/internal/desktop.Assembly.Prefixes";
export const ASSEMBLY_PREVIEW = "github.com/kieranajp/qrouton/internal/desktop.Assembly.Preview";
export const ASSEMBLY_RUNNERS = "github.com/kieranajp/qrouton/internal/desktop.Assembly.Runners";
export const CHROME_SNAPSHOT = "github.com/kieranajp/qrouton/internal/desktop.Chrome.Snapshot";
export const FIRST_RUN_CHOOSE_ROOT = "github.com/kieranajp/qrouton/internal/desktop.FirstRun.ChooseRoot";
export const FIRST_RUN_LOGIN = "github.com/kieranajp/qrouton/internal/desktop.FirstRun.Login";
export const FIRST_RUN_SAVE = "github.com/kieranajp/qrouton/internal/desktop.FirstRun.Save";
export const ORGS_LIST = "github.com/kieranajp/qrouton/internal/desktop.Orgs.List";
export const PICKER_CANCEL = "github.com/kieranajp/qrouton/internal/desktop.Picker.Cancel";
export const PICKER_CONFIRM = "github.com/kieranajp/qrouton/internal/desktop.Picker.Confirm";
export const PICKER_ESCALATE = "github.com/kieranajp/qrouton/internal/desktop.Picker.Escalate";
export const PICKER_LOAD = "github.com/kieranajp/qrouton/internal/desktop.Picker.Load";
export const REPOSITORIES_CACHED = "github.com/kieranajp/qrouton/internal/desktop.Repositories.Cached";
export const REPOSITORIES_REFRESH = "github.com/kieranajp/qrouton/internal/desktop.Repositories.Refresh";
export const REPOSITORIES_SELECT = "github.com/kieranajp/qrouton/internal/desktop.Repositories.Select";
export const SESSIONS_CLEANUP = "github.com/kieranajp/qrouton/internal/desktop.Sessions.Cleanup";
export const SESSIONS_REVEAL = "github.com/kieranajp/qrouton/internal/desktop.Sessions.Reveal";
export const SESSIONS_REVEAL_PATH = "github.com/kieranajp/qrouton/internal/desktop.Sessions.RevealPath";
export const SESSIONS_SHOW = "github.com/kieranajp/qrouton/internal/desktop.Sessions.Show";
export const SESSIONS_UNCOMMITTED = "github.com/kieranajp/qrouton/internal/desktop.Sessions.Uncommitted";
export const SETTINGS_LOAD = "github.com/kieranajp/qrouton/internal/desktop.Settings.Load";
export const SETTINGS_QUIT = "github.com/kieranajp/qrouton/internal/desktop.Settings.Quit";
export const SETTINGS_SAVE = "github.com/kieranajp/qrouton/internal/desktop.Settings.Save";
export const TERM_RESIZE = "github.com/kieranajp/qrouton/internal/desktop.Term.Resize";
export const TERM_START = "github.com/kieranajp/qrouton/internal/desktop.Term.Start";
export const TERM_WRITE = "github.com/kieranajp/qrouton/internal/desktop.Term.Write";
export const WINDOWS_CLOSE = "github.com/kieranajp/qrouton/internal/desktop.Windows.Close";
export const WINDOWS_CONTENT = "github.com/kieranajp/qrouton/internal/desktop.Windows.Content";
export const WINDOWS_OPEN_DOCUMENT = "github.com/kieranajp/qrouton/internal/desktop.Windows.OpenDocument";
export const WINDOWS_OPEN_SHELL = "github.com/kieranajp/qrouton/internal/desktop.Windows.OpenShell";
export const WINDOWS_RENDER_DIAGRAMS = "github.com/kieranajp/qrouton/internal/desktop.Windows.RenderDiagrams";
export const WINDOWS_REPORT_VIEWPORT = "github.com/kieranajp/qrouton/internal/desktop.Windows.ReportViewport";
export const WINDOWS_RESIZE = "github.com/kieranajp/qrouton/internal/desktop.Windows.Resize";
export const WINDOWS_SELECT = "github.com/kieranajp/qrouton/internal/desktop.Windows.Select";
export const WINDOWS_START = "github.com/kieranajp/qrouton/internal/desktop.Windows.Start";
export const WINDOWS_SURFACES = "github.com/kieranajp/qrouton/internal/desktop.Windows.Surfaces";
export const WINDOWS_WRITE = "github.com/kieranajp/qrouton/internal/desktop.Windows.Write";

export const ASSEMBLY_PROGRESS_EVENT = "assembly:progress";
export const ASSEMBLY_REQUESTED_EVENT = "assembly:requested";
export const CHROME_EVENT = "chrome:update";
export const ORGS_CHANGED_EVENT = "orgs:changed";
export const PTY_DATA_EVENT = "pty:data:";
export const PTY_EXIT_EVENT = "pty:exit:";
export const REPOS_REFRESH_EVENT = "repos:refresh";
export const WINDOW_CONTENT_EVENT = "window:content:";
export const WINDOW_DATA_EVENT = "window:data:";
export const WINDOW_DIAGRAM_EVENT = "window:diagram:";
export const WINDOW_EXIT_EVENT = "window:exit:";
export const WINDOWS_EVENT = "window:open";

/** @type {{mode: string, phase: string, identity: string, branch: string, slug: string, terminal: string, sessions: any[], documents: any[], repositoryDocuments: any[], repos: any[], activity: string, agents: {provider: string, attention_known: boolean, children_known: boolean, parents_known: boolean, outcomes_known: boolean, agents: any[]}, stages: {research: boolean, plan: boolean, implement: boolean}, root: string, picker: boolean, welcoming: boolean}} */
export const CHROME_DEFAULTS = {
  mode: "",
  phase: "",
  identity: "",
  branch: "",
  slug: "",
  terminal: "",
  sessions: [],
  documents: [],
  repositoryDocuments: [],
  repos: [],
  activity: "",
  agents: {
    provider: "",
    attention_known: false,
    children_known: false,
    parents_known: false,
    outcomes_known: false,
    agents: [],
  },
  stages: {
    research: false,
    plan: false,
    implement: false,
  },
  root: "",
  picker: false,
  welcoming: false,
};
