// Code generated by internal/desktop/bridge. DO NOT EDIT.

export const ASSEMBLY_BEGIN = "github.com/kieranajp/qrouton/internal/desktop.Assembly.Begin";
export const ASSEMBLY_CHECK = "github.com/kieranajp/qrouton/internal/desktop.Assembly.Check";
export const ASSEMBLY_CHECK_SLUG = "github.com/kieranajp/qrouton/internal/desktop.Assembly.CheckSlug";
export const ASSEMBLY_CREATE = "github.com/kieranajp/qrouton/internal/desktop.Assembly.Create";
export const ASSEMBLY_END = "github.com/kieranajp/qrouton/internal/desktop.Assembly.End";
export const ASSEMBLY_FETCH = "github.com/kieranajp/qrouton/internal/desktop.Assembly.Fetch";
export const ASSEMBLY_PENDING = "github.com/kieranajp/qrouton/internal/desktop.Assembly.Pending";
export const ASSEMBLY_PREFIXES = "github.com/kieranajp/qrouton/internal/desktop.Assembly.Prefixes";
export const ASSEMBLY_PREVIEW = "github.com/kieranajp/qrouton/internal/desktop.Assembly.Preview";
export const ASSEMBLY_RUNNERS = "github.com/kieranajp/qrouton/internal/desktop.Assembly.Runners";
export const BUG_REPORTS_CANCEL = "github.com/kieranajp/qrouton/internal/desktop.BugReports.Cancel";
export const BUG_REPORTS_CONFIRM = "github.com/kieranajp/qrouton/internal/desktop.BugReports.Confirm";
export const BUG_REPORTS_LOAD = "github.com/kieranajp/qrouton/internal/desktop.BugReports.Load";
export const CHROME_SNAPSHOT = "github.com/kieranajp/qrouton/internal/desktop.Chrome.Snapshot";
export const FIRST_RUN_CHOOSE_ROOT = "github.com/kieranajp/qrouton/internal/desktop.FirstRun.ChooseRoot";
export const FIRST_RUN_LOGIN = "github.com/kieranajp/qrouton/internal/desktop.FirstRun.Login";
export const FIRST_RUN_SAVE = "github.com/kieranajp/qrouton/internal/desktop.FirstRun.Save";
export const ORGS_LIST = "github.com/kieranajp/qrouton/internal/desktop.Orgs.List";
export const PICKER_CANCEL = "github.com/kieranajp/qrouton/internal/desktop.Picker.Cancel";
export const PICKER_CONFIRM = "github.com/kieranajp/qrouton/internal/desktop.Picker.Confirm";
export const PICKER_ESCALATE = "github.com/kieranajp/qrouton/internal/desktop.Picker.Escalate";
export const PICKER_LOAD = "github.com/kieranajp/qrouton/internal/desktop.Picker.Load";
export const PRESENTER_CLOSE = "github.com/kieranajp/qrouton/internal/desktop.Presenter.Close";
export const PRESENTER_NOTE = "github.com/kieranajp/qrouton/internal/desktop.Presenter.Note";
export const PRESENTER_OPEN = "github.com/kieranajp/qrouton/internal/desktop.Presenter.Open";
export const PRESENTER_SHOW = "github.com/kieranajp/qrouton/internal/desktop.Presenter.Show";
export const REPOSITORIES_BRANCHES = "github.com/kieranajp/qrouton/internal/desktop.Repositories.Branches";
export const REPOSITORIES_CACHED = "github.com/kieranajp/qrouton/internal/desktop.Repositories.Cached";
export const REPOSITORIES_REFRESH = "github.com/kieranajp/qrouton/internal/desktop.Repositories.Refresh";
export const REPOSITORIES_SELECT = "github.com/kieranajp/qrouton/internal/desktop.Repositories.Select";
export const SESSIONS_CLEANUP = "github.com/kieranajp/qrouton/internal/desktop.Sessions.Cleanup";
export const SESSIONS_COPY_IMAGE = "github.com/kieranajp/qrouton/internal/desktop.Sessions.CopyImage";
export const SESSIONS_CYCLE_STICKER = "github.com/kieranajp/qrouton/internal/desktop.Sessions.CycleSticker";
export const SESSIONS_RELOAD = "github.com/kieranajp/qrouton/internal/desktop.Sessions.Reload";
export const SESSIONS_REVEAL = "github.com/kieranajp/qrouton/internal/desktop.Sessions.Reveal";
export const SESSIONS_REVEAL_PATH = "github.com/kieranajp/qrouton/internal/desktop.Sessions.RevealPath";
export const SESSIONS_SHOW = "github.com/kieranajp/qrouton/internal/desktop.Sessions.Show";
export const SESSIONS_UNCOMMITTED = "github.com/kieranajp/qrouton/internal/desktop.Sessions.Uncommitted";
export const SETTINGS_LOAD = "github.com/kieranajp/qrouton/internal/desktop.Settings.Load";
export const SETTINGS_QUIT = "github.com/kieranajp/qrouton/internal/desktop.Settings.Quit";
export const SETTINGS_SAVE = "github.com/kieranajp/qrouton/internal/desktop.Settings.Save";
export const TERM_RESIZE = "github.com/kieranajp/qrouton/internal/desktop.Term.Resize";
export const TERM_START = "github.com/kieranajp/qrouton/internal/desktop.Term.Start";
export const TERM_WRITE = "github.com/kieranajp/qrouton/internal/desktop.Term.Write";
export const UPDATES_STATUS = "github.com/kieranajp/qrouton/internal/desktop.Updates.Status";
export const WINDOWS_CLOSE = "github.com/kieranajp/qrouton/internal/desktop.Windows.Close";
export const WINDOWS_CONTENT = "github.com/kieranajp/qrouton/internal/desktop.Windows.Content";
export const WINDOWS_FOCUS_IMAGE = "github.com/kieranajp/qrouton/internal/desktop.Windows.FocusImage";
export const WINDOWS_OPEN_DOCUMENT = "github.com/kieranajp/qrouton/internal/desktop.Windows.OpenDocument";
export const WINDOWS_OPEN_SHELL = "github.com/kieranajp/qrouton/internal/desktop.Windows.OpenShell";
export const WINDOWS_RENDER_DIAGRAMS = "github.com/kieranajp/qrouton/internal/desktop.Windows.RenderDiagrams";
export const WINDOWS_REORDER = "github.com/kieranajp/qrouton/internal/desktop.Windows.Reorder";
export const WINDOWS_REPORT_VIEWPORT = "github.com/kieranajp/qrouton/internal/desktop.Windows.ReportViewport";
export const WINDOWS_RESIZE = "github.com/kieranajp/qrouton/internal/desktop.Windows.Resize";
export const WINDOWS_SELECT = "github.com/kieranajp/qrouton/internal/desktop.Windows.Select";
export const WINDOWS_START = "github.com/kieranajp/qrouton/internal/desktop.Windows.Start";
export const WINDOWS_SURFACES = "github.com/kieranajp/qrouton/internal/desktop.Windows.Surfaces";
export const WINDOWS_WRITE = "github.com/kieranajp/qrouton/internal/desktop.Windows.Write";

export const ASSEMBLY_PROGRESS_EVENT = "assembly:progress";
export const ASSEMBLY_REQUESTED_EVENT = "assembly:requested";
export const CHROME_EVENT = "chrome:update";
export const ORGS_CHANGED_EVENT = "orgs:changed";
export const PRESENTER_CLOSED_EVENT = "presenter:closed";
export const PRESENTER_NOTES_EVENT = "presenter:notes";
export const PTY_DATA_EVENT = "pty:data:";
export const PTY_EXIT_EVENT = "pty:exit:";
export const REPOS_REFRESH_EVENT = "repos:refresh";
export const UPDATE_EVENT = "update:status";
export const WINDOW_CONTENT_EVENT = "window:content:";
export const WINDOW_DATA_EVENT = "window:data:";
export const WINDOW_DIAGRAM_EVENT = "window:diagram:";
export const WINDOW_EXIT_EVENT = "window:exit:";
export const WINDOWS_EVENT = "window:open";

/** @typedef {"working"|"waiting"|"idle"|"turn-ended"} Activity */
export const ACTIVITIES = Object.freeze({
  WORKING: "working",
  WAITING: "waiting",
  IDLE: "idle",
  TURN_ENDED: "turn-ended",
});

/** @typedef {"needs-you"|"none"|"unknown"} AgentAttention */
export const AGENT_ATTENTION = Object.freeze({
  NEEDS_YOU: "needs-you",
  NONE: "none",
  UNKNOWN: "unknown",
});

/** @typedef {"full"|"root"|"none"} AgentCoverage */
export const AGENT_COVERAGE = Object.freeze({
  FULL: "full",
  ROOT: "root",
  NONE: "none",
});

/** @typedef {"Orchestrator"|"Lead"|"Specialist"|"Role unavailable"} AgentRole */
export const AGENT_ROLES = Object.freeze({
  ORCHESTRATOR: "Orchestrator",
  LEAD: "Lead",
  SPECIALIST: "Specialist",
  UNAVAILABLE: "Role unavailable",
});

/** @typedef {"Waiting for you"|"Working"|"Idle"|"Active"|"Finished"|"Failed"} AgentState */
export const AGENT_STATES = Object.freeze({
  WAITING: "Waiting for you",
  WORKING: "Working",
  IDLE: "Idle",
  ACTIVE: "Active",
  FINISHED: "Finished",
  FAILED: "Failed",
});

/** @typedef {"PLAN"|"SPEC"|"RESEARCH"|"NOTE"|"EXPLAINER"} ArtifactKind */
export const ARTIFACT_KINDS = Object.freeze({
  PLAN: "PLAN",
  SPEC: "SPEC",
  RESEARCH: "RESEARCH",
  NOTE: "NOTE",
  EXPLAINER: "EXPLAINER",
});

/** @typedef {"pending"|"posting"|"created"|"cancelled"|"expired"|"failed"|"unknown"} BugReportStatus */
export const BUG_REPORT_STATUSES = Object.freeze({
  PENDING: "pending",
  POSTING: "posting",
  CREATED: "created",
  CANCELLED: "cancelled",
  EXPIRED: "expired",
  FAILED: "failed",
  UNKNOWN: "unknown",
});

/** @typedef {"diff"|"images"|"markdown"} DocumentFormat */
export const DOCUMENT_FORMATS = Object.freeze({
  DIFF: "diff",
  IMAGES: "images",
  MARKDOWN: "markdown",
});

/** @typedef {"name"|"branchDescription"|"ticket"|"repos"} DraftField */
export const DRAFT_FIELDS = Object.freeze({
  NAME: "name",
  BRANCH_DESCRIPTION: "branchDescription",
  TICKET: "ticket",
  REPOS: "repos",
});

/** @typedef {"ASSISTANT"|"RPI"} ModeLabel */
export const MODE_LABELS = Object.freeze({
  ASSISTANT: "ASSISTANT",
  RPI: "RPI",
});

/** @typedef {"started"|"completed"|"failed"|"advanced"} ProgressStatus */
export const PROGRESS_STATUSES = Object.freeze({
  STARTED: "started",
  COMPLETED: "completed",
  FAILED: "failed",
  ADVANCED: "advanced",
});

/** @typedef {"started"|"succeeded"|"failed"|"complete"} RefreshState */
export const REFRESH_STATES = Object.freeze({
  STARTED: "started",
  SUCCEEDED: "succeeded",
  FAILED: "failed",
  COMPLETE: "complete",
});

/** @typedef {"editing"|"reference"} RepoRole */
export const REPO_ROLES = Object.freeze({
  EDITING: "editing",
  REFERENCE: "reference",
});

/** @typedef {"rpi"|"assistant"} SessionMode */
export const SESSION_MODES = Object.freeze({
  RPI: "rpi",
  ASSISTANT: "assistant",
});

/** @typedef {"orgs"|"root"|"editor"|"launch"|"linear"|"star"|"bookmark"|"question"|"exclamation"|"thoughts"} SettingsField */
export const SETTINGS_FIELDS = Object.freeze({
  ORGS: "orgs",
  ROOT: "root",
  EDITOR: "editor",
  LAUNCH: "launch",
  LINEAR: "linear",
  STAR: "star",
  BOOKMARK: "bookmark",
  QUESTION: "question",
  EXCLAMATION: "exclamation",
  THOUGHTS: "thoughts",
});

/** @typedef {"star"|"bookmark"|"question"|"exclamation"} Sticker */
export const STICKER_IDS = Object.freeze({
  STAR: "star",
  BOOKMARK: "bookmark",
  QUESTION: "question",
  EXCLAMATION: "exclamation",
});

/** @typedef {"running"|"succeeded"|"failed"|"waiting"} TabStatus */
export const TAB_STATUSES = Object.freeze({
  RUNNING: "running",
  SUCCEEDED: "succeeded",
  FAILED: "failed",
  WAITING: "waiting",
});

/** @typedef {"terminal"|"document"} WindowKind */
export const WINDOW_KINDS = Object.freeze({
  TERMINAL: "terminal",
  DOCUMENT: "document",
});

export const AGENT_ROOT_ID = "root";

/** @type {{bugReportID: string, bugReportStatus: string, bugReportLabel: string, mode: string, phase: string, identity: string, branch: string, slug: string, terminal: string, sessions: any[], documents: any[], repositoryDocuments: any[], repos: any[], activity: string, agents: {provider: string, provider_label: string, attention_known: boolean, children_known: boolean, parents_known: boolean, outcomes_known: boolean, agents: any[]}, stages: {research: boolean, plan: boolean, implement: boolean}, root: string, picker: boolean, welcoming: boolean, stickerLabels: {star: string, bookmark: string, question: string, exclamation: string}}} */
export const CHROME_DEFAULTS = {
  bugReportID: "",
  bugReportStatus: "",
  bugReportLabel: "",
  mode: "",
  phase: "",
  identity: "",
  branch: "",
  slug: "",
  terminal: "",
  sessions: [],
  documents: [],
  repositoryDocuments: [],
  repos: [],
  activity: "",
  agents: {
    provider: "",
    provider_label: "",
    attention_known: false,
    children_known: false,
    parents_known: false,
    outcomes_known: false,
    agents: [],
  },
  stages: {
    research: false,
    plan: false,
    implement: false,
  },
  root: "",
  picker: false,
  welcoming: false,
  stickerLabels: {
    star: "",
    bookmark: "",
    question: "",
    exclamation: "",
  },
};
